version: '3.7'

networks:
  private:
    driver: bridge

services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - private

  redis:
    hostname: redis
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - private
      
  rest:
    build:
      context: .
      dockerfile: ./docker/local.Dockerfile
    ports:
      - '8080:8080'
    env_file: ./apps/rest/.env
    working_dir: "/usr/app/apps/rest"
    volumes:
      - .:/usr/app
    networks:
      - private

  consumer:
    build:
      context: .
      dockerfile: ./docker/local.Dockerfile
    env_file: ./apps/consumer/.env
    working_dir: "/usr/app/apps/consumer"
    volumes:
      - .:/usr/app
    networks:
      - private
